Repository microsoft/winget-cli, pull requests merged in 2021-09, with the labels that each got.

#1441 Support for x64 on ARM64
  .github/actions/spelling/expect.txt
  src/AppInstallerCommonCore/Architecture.cpp
Labels: Issue-Feature

#1467 doc/Settings.md: Add missing "a"
  doc/Settings.md
Labels: Issue-Docs

#1470 Source resilience
  .github/actions/spelling/allow.txt
  doc/Settings.md
  schemas/JSON/settings/settings.schema.0.2.json
  src/AppInstallerCLICore/AppInstallerCLICore.vcxproj
  src/AppInstallerCLICore/Command.cpp
  src/AppInstallerCLICore/Commands/ExportCommand.cpp
  src/AppInstallerCLICore/Commands/InstallCommand.cpp
  src/AppInstallerCLICore/Commands/ListCommand.cpp
  src/AppInstallerCLICore/Commands/SearchCommand.cpp
  src/AppInstallerCLICore/Commands/ShowCommand.cpp
  src/AppInstallerCLICore/Commands/UninstallCommand.cpp
  src/AppInstallerCLICore/Commands/UpgradeCommand.cpp
  src/AppInstallerCLICore/ExecutionContext.h
  src/AppInstallerCLICore/Resources.h
  src/AppInstallerCLICore/Workflows/ImportExportFlow.cpp
  src/AppInstallerCLICore/Workflows/WorkflowBase.cpp
  src/AppInstallerCLICore/Workflows/WorkflowBase.h
  src/AppInstallerCLIE2ETests/BaseCommand.cs
  src/AppInstallerCLIE2ETests/Constants.cs
  src/AppInstallerCLIE2ETests/FeaturesCommand.cs
  src/AppInstallerCLIE2ETests/InstallCommand.cs
  src/AppInstallerCLIE2ETests/SearchCommand.cs
  src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
  src/AppInstallerCLITests/CompositeSource.cpp
  src/AppInstallerCLITests/Sources.cpp
  src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj
  src/AppInstallerCommonCore/AppInstallerTelemetry.cpp
  src/AppInstallerCommonCore/ExperimentalFeature.cpp
  src/AppInstallerCommonCore/Public/AppInstallerErrors.h
  src/AppInstallerCommonCore/Public/AppInstallerTelemetry.h
  src/AppInstallerCommonCore/Public/winget/ExperimentalFeature.h
  src/AppInstallerCommonCore/Public/winget/UserSettings.h
  src/AppInstallerCommonCore/UserSettings.cpp
  src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj
  src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj.filters
  src/AppInstallerRepositoryCore/CompositeSource.cpp
  src/AppInstallerRepositoryCore/CompositeSource.h
  src/AppInstallerRepositoryCore/Microsoft/ConfigurableTestSourceFactory.cpp
  src/AppInstallerRepositoryCore/Microsoft/ConfigurableTestSourceFactory.h
  src/AppInstallerRepositoryCore/Public/AppInstallerRepositorySearch.h
  src/AppInstallerRepositoryCore/Public/AppInstallerRepositorySource.h
  src/AppInstallerRepositoryCore/RepositorySource.cpp
  src/Microsoft.Management.Deployment/PackageCatalog.cpp
Labels: Issue-Bug

#1473 Ensure available packages match with a single installed package
  src/AppInstallerCLICore/Workflows/InstallFlow.cpp
  src/AppInstallerCLICore/Workflows/WorkflowBase.h
  src/AppInstallerRepositoryCore/CompositeSource.cpp
Labels: Issue-Bug
