Repository microsoft/winget-cli, pull requests merged in 2021-05, with the labels that each got.

#917 Correct doc'd behaviour for `winget settings`
  doc/Settings.md
Labels: Issue-Docs

#928 Set url max length to 2048
  schemas/JSON/manifests/preview/manifest.0.1.0.json
  schemas/JSON/manifests/v1.0.0/manifest.defaultLocale.1.0.0.json
  schemas/JSON/manifests/v1.0.0/manifest.installer.1.0.0.json
  schemas/JSON/manifests/v1.0.0/manifest.locale.1.0.0.json
  schemas/JSON/manifests/v1.0.0/manifest.singleton.1.0.0.json
Labels: Issue-Feature

#966 Fix a few polish items
  .github/actions/spelling/allow.txt
  .github/actions/spelling/expect.txt
  src/AppInstallerCLICore/ExecutionReporter.cpp
  src/AppInstallerCLICore/VTSupport.cpp
  src/AppInstallerCLICore/VTSupport.h
  src/AppInstallerCLICore/Workflows/WorkflowBase.cpp
  src/AppInstallerCLICore/Workflows/WorkflowBase.h
  src/AppInstallerCLITests/Strings.cpp
  src/AppInstallerCommonCore/AppInstallerStrings.cpp
  src/AppInstallerCommonCore/AppInstallerTelemetry.cpp
  src/AppInstallerCommonCore/Public/AppInstallerRuntime.h
  src/AppInstallerCommonCore/Public/AppInstallerStrings.h
  src/AppInstallerCommonCore/Public/AppInstallerTelemetry.h
  src/AppInstallerCommonCore/Registry.cpp
  src/AppInstallerCommonCore/Runtime.cpp
  src/AppInstallerRepositoryCore/Microsoft/ARPHelper.cpp
Labels: Area-Accessibility, Issue-Bug
