Repository microsoft/winget-cli, pull requests merged in 2021-08, with the labels that each got.

#1165 Show dependencies feature #1012
  .github/actions/spelling/expect.txt
  doc/Settings.md
  src/AppInstallerCLICore/AppInstallerCLICore.vcxproj
  src/AppInstallerCLICore/AppInstallerCLICore.vcxproj.filters
  src/AppInstallerCLICore/Commands/UninstallCommand.cpp
  src/AppInstallerCLICore/Commands/UpgradeCommand.cpp
  src/AppInstallerCLICore/Commands/ValidateCommand.cpp
  src/AppInstallerCLICore/ExecutionContextData.h
  src/AppInstallerCLICore/ExecutionReporter.cpp
  src/AppInstallerCLICore/ExecutionReporter.h
  src/AppInstallerCLICore/Resources.h
  src/AppInstallerCLICore/Workflows/DependenciesFlow.cpp
  src/AppInstallerCLICore/Workflows/DependenciesFlow.h
  src/AppInstallerCLICore/Workflows/InstallFlow.cpp
  src/AppInstallerCLICore/Workflows/InstallFlow.h
  src/AppInstallerCLICore/Workflows/ShowFlow.cpp
  src/AppInstallerCLICore/Workflows/UpdateFlow.cpp
  src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
  src/AppInstallerCLITests/AppInstallerCLITests.vcxproj
  src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters
  src/AppInstallerCLITests/RestInterface_1_0.cpp
  src/AppInstallerCLITests/TestData/ImportFile-Good-Dependencies.json
  src/AppInstallerCLITests/TestData/Installer_Exe_Dependencies.yaml
  src/AppInstallerCLITests/TestData/Installer_Exe_DependenciesMultideclaration.yaml
  src/AppInstallerCLITests/TestData/Installer_Exe_DependenciesOnRoot.yaml
  src/AppInstallerCLITests/TestData/Installer_Msi_WFDependency.yaml
  src/AppInstallerCLITests/TestData/Manifest-Good-AllDependencyTypes.yaml
  src/AppInstallerCLITests/TestData/UpdateFlowTest_ExeDependencies.yaml
  src/AppInstallerCLITests/WorkFlow.cpp
  src/AppInstallerCLITests/YamlManifest.cpp
  src/AppInstallerCommonCore/ExperimentalFeature.cpp
  src/AppInstallerCommonCore/Manifest/ManifestYamlPopulator.cpp
  src/AppInstallerCommonCore/Public/winget/ExperimentalFeature.h
  src/AppInstallerCommonCore/Public/winget/ManifestCommon.h
  src/AppInstallerCommonCore/Public/winget/ManifestInstaller.h
  src/AppInstallerCommonCore/Public/winget/ManifestYamlPopulator.h
  src/AppInstallerCommonCore/Public/winget/UserSettings.h
  src/AppInstallerCommonCore/UserSettings.cpp
  src/AppInstallerRepositoryCore/Rest/Schema/1_0/Json/ManifestDeserializer.cpp
  src/AppInstallerRepositoryCore/Rest/Schema/1_0/Json/ManifestDeserializer.h
Labels: Issue-Feature

#1367 Show the version number during install.
  src/AppInstallerCLICore/Workflows/WorkflowBase.cpp
Labels: Issue-Feature, Area-User-Interface

#1342 Add an install queue and an ISource for querying Installing packages.
  .github/actions/spelling/allow.txt
  .github/actions/spelling/expect.txt
  src/AppInstallerCLICore/AppInstallerCLICore.vcxproj
  src/AppInstallerCLICore/AppInstallerCLICore.vcxproj.filters
  src/AppInstallerCLICore/COMContext.cpp
  src/AppInstallerCLICore/COMContext.h
  src/AppInstallerCLICore/ContextOrchestrator.cpp
  src/AppInstallerCLICore/ContextOrchestrator.h
  src/AppInstallerCLICore/ExecutionContext.cpp
  src/AppInstallerCLICore/ExecutionContext.h
  src/AppInstallerCommonCore/AppInstallerTelemetry.cpp
  src/AppInstallerCommonCore/Public/AppInstallerTelemetry.h
  src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj
  src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj.filters
  src/AppInstallerRepositoryCore/Microsoft/PredefinedWriteableSourceFactory.cpp
  src/AppInstallerRepositoryCore/Microsoft/PredefinedWriteableSourceFactory.h
  src/AppInstallerRepositoryCore/Microsoft/SQLiteIndexSource.cpp
  src/AppInstallerRepositoryCore/Microsoft/SQLiteIndexSource.h
  src/AppInstallerRepositoryCore/Public/AppInstallerRepositorySearch.h
  src/AppInstallerRepositoryCore/Public/AppInstallerRepositorySource.h
  src/AppInstallerRepositoryCore/RepositorySource.cpp
  src/Microsoft.Management.Deployment/Converters.cpp
  src/Microsoft.Management.Deployment/Converters.h
  src/Microsoft.Management.Deployment/Helpers.h
  src/Microsoft.Management.Deployment/PackageCatalog.cpp
  src/Microsoft.Management.Deployment/PackageManager.cpp
  src/Microsoft.Management.Deployment/PackageManager.h
  src/Microsoft.Management.Deployment/PackageManager.idl
Labels: Needs-Author-Feedback

#1390 Display count of available upgrades
  src/AppInstallerCLICore/Resources.h
  src/AppInstallerCLICore/Workflows/WorkflowBase.cpp
  src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
Labels: Issue-Feature
