Repository microsoft/winget-cli, pull requests merged in 2022-08, with the labels that each got.

#2390 Add command aliases
  src/AppInstallerCLICore/Command.cpp
  src/AppInstallerCLICore/Command.h
  src/AppInstallerCLICore/Commands/CompleteCommand.h
  src/AppInstallerCLICore/Commands/ExperimentalCommand.h
  src/AppInstallerCLICore/Commands/InstallCommand.h
  src/AppInstallerCLICore/Commands/ListCommand.h
  src/AppInstallerCLICore/Commands/SearchCommand.h
  src/AppInstallerCLICore/Commands/SettingsCommand.h
  src/AppInstallerCLICore/Commands/ShowCommand.h
  src/AppInstallerCLICore/Commands/SourceCommand.h
  src/AppInstallerCLICore/Commands/UninstallCommand.h
  src/AppInstallerCLICore/Commands/UpgradeCommand.h
  src/AppInstallerCLICore/Resources.h
  src/AppInstallerCLIE2ETests/SearchCommand.cs
  src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
  src/AppInstallerCLITests/Command.cpp
  src/AppInstallerCommonCore/AppInstallerStrings.cpp
  src/AppInstallerCommonCore/Public/AppInstallerStrings.h
Labels: Issue-Feature

#2413 Ensure default values are passed to nested installers within zip
  src/AppInstallerCLICore/Resources.h
  src/AppInstallerCLICore/Workflows/ArchiveFlow.cpp
  src/AppInstallerCLICore/Workflows/DependenciesFlow.cpp
  src/AppInstallerCLICore/Workflows/DownloadFlow.cpp
  src/AppInstallerCLICore/Workflows/InstallFlow.cpp
  src/AppInstallerCLICore/Workflows/ManifestComparator.cpp
  src/AppInstallerCLICore/Workflows/PortableFlow.cpp
  src/AppInstallerCLICore/Workflows/ShowFlow.cpp
  src/AppInstallerCLICore/Workflows/UpdateFlow.cpp
  src/AppInstallerCLICore/Workflows/WorkflowBase.cpp
  src/AppInstallerCLIE2ETests/InstallCommand.cs
  src/AppInstallerCLIE2ETests/ListCommand.cs
  src/AppInstallerCLIE2ETests/Test.runsettings
  src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
  src/AppInstallerCLITests/ARPChanges.cpp
  src/AppInstallerCLITests/AppInstallerCLITests.vcxproj
  src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters
  src/AppInstallerCLITests/ManifestComparator.cpp
  src/AppInstallerCLITests/RestInterface_1_0.cpp
  src/AppInstallerCLITests/RestInterface_1_1.cpp
  src/AppInstallerCLITests/SQLiteIndex.cpp
  src/AppInstallerCLITests/TestData/InstallFlowTest_Zip_UnsupportedNestedInstaller.yaml
  src/AppInstallerCLITests/WorkFlow.cpp
  src/AppInstallerCLITests/YamlManifest.cpp
  src/AppInstallerCommonCore/Manifest/Manifest.cpp
  src/AppInstallerCommonCore/Manifest/ManifestCommon.cpp
  src/AppInstallerCommonCore/Manifest/ManifestValidation.cpp
  src/AppInstallerCommonCore/Manifest/ManifestYamlPopulator.cpp
  src/AppInstallerCommonCore/Public/winget/ManifestCommon.h
  src/AppInstallerCommonCore/Public/winget/ManifestInstaller.h
  src/AppInstallerRepositoryCore/Rest/Schema/1_0/Json/ManifestDeserializer_1_0.cpp
  src/AppInstallerRepositoryCore/Rest/Schema/1_1/Json/ManifestDeserializer_1_1.cpp
Labels: Issue-Bug

#1814 Add prompts when installer aborts terminal or needs install location
  doc/Settings.md
  schemas/JSON/settings/settings.schema.0.2.json
  src/AppInstallerCLICore/AppInstallerCLICore.vcxproj
  src/AppInstallerCLICore/AppInstallerCLICore.vcxproj.filters
  src/AppInstallerCLICore/Argument.cpp
  src/AppInstallerCLICore/COMContext.h
  src/AppInstallerCLICore/Command.cpp
  src/AppInstallerCLICore/ExecutionArgs.h
  src/AppInstallerCLICore/ExecutionContext.h
  src/AppInstallerCLICore/ExecutionReporter.cpp
  src/AppInstallerCLICore/ExecutionReporter.h
  src/AppInstallerCLICore/Resources.h
  src/AppInstallerCLICore/Workflows/InstallFlow.cpp
  src/AppInstallerCLICore/Workflows/InstallFlow.h
  src/AppInstallerCLICore/Workflows/PromptFlow.cpp
  src/AppInstallerCLICore/Workflows/PromptFlow.h
  src/AppInstallerCLICore/Workflows/SourceFlow.cpp
  src/AppInstallerCLICore/Workflows/WorkflowBase.cpp
  src/AppInstallerCLICore/Workflows/WorkflowBase.h
  src/AppInstallerCLIE2ETests/Constants.cs
  src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
  src/AppInstallerCLITests/AppInstallerCLITests.vcxproj
  src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters
  src/AppInstallerCLITests/TestData/InstallFlowTest_AbortsTerminal.yaml
  src/AppInstallerCLITests/TestData/InstallFlowTest_InstallLocationRequired.yaml
  src/AppInstallerCLITests/WorkFlow.cpp
  src/AppInstallerCommonCore/Errors.cpp
  src/AppInstallerCommonCore/Public/AppInstallerErrors.h
  src/AppInstallerCommonCore/Public/winget/UserSettings.h
  src/AppInstallerCommonCore/UserSettings.cpp
Labels: Issue-Feature, Area-Manifest

#2431 Update Labels from Hash Command
  src/AppInstallerCLICore/Commands/HashCommand.cpp
Labels: Issue-Feature

#2418 Use `UpgradeCode` for matching MSI apps
  .github/actions/spelling/allow.txt
  .github/actions/spelling/expect.txt
  src/AppInstallerCLICore/Workflows/InstallFlow.cpp
  src/AppInstallerCLIE2ETests/ListCommand.cs
  src/AppInstallerCLIE2ETests/TestData/Manifests/TestMsiInstaller_UpgradeCode.yaml
  src/AppInstallerRepositoryCore/ARPCorrelation.cpp
  src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj
  src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj.filters
  src/AppInstallerRepositoryCore/CompositeSource.cpp
  src/AppInstallerRepositoryCore/Microsoft/ARPHelper.cpp
  src/AppInstallerRepositoryCore/Microsoft/ARPHelper.h
  src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/Interface.h
  src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/Interface_1_0.cpp
  src/AppInstallerRepositoryCore/Microsoft/Schema/1_1/Interface_1_1.cpp
  src/AppInstallerRepositoryCore/Microsoft/Schema/1_2/Interface_1_2.cpp
  src/AppInstallerRepositoryCore/Microsoft/Schema/1_3/Interface.h
  src/AppInstallerRepositoryCore/Microsoft/Schema/1_4/Interface_1_4.cpp
  src/AppInstallerRepositoryCore/Microsoft/Schema/1_6/Interface.h
  src/AppInstallerRepositoryCore/Microsoft/Schema/1_6/Interface_1_6.cpp
  src/AppInstallerRepositoryCore/Microsoft/Schema/1_6/SearchResultsTable.h
  src/AppInstallerRepositoryCore/Microsoft/Schema/1_6/SearchResultsTable_1_6.cpp
  src/AppInstallerRepositoryCore/Microsoft/Schema/1_6/UpgradeCodeTable.h
  src/AppInstallerRepositoryCore/Microsoft/Schema/Version.cpp
  src/AppInstallerRepositoryCore/Public/winget/RepositorySearch.h
  src/AppInstallerRepositoryCore/RepositorySearch.cpp
Labels: Issue-Feature, Area-Manifest

#2401 Add support for installing portables without developer mode and running as admin
  src/AppInstallerCLICore/ExecutionContextData.h
  src/AppInstallerCLICore/Workflows/PortableFlow.cpp
  src/AppInstallerCLICore/Workflows/PortableFlow.h
  src/AppInstallerCLICore/Workflows/UninstallFlow.cpp
  src/AppInstallerCLITests/AppInstallerCLITests.vcxproj
  src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters
  src/AppInstallerCLITests/PortableEntry.cpp
  src/AppInstallerCLITests/TestData/InstallFlowTest_Portable.yaml
  src/AppInstallerCLITests/TestData/UpdateFlowTest_Portable.yaml
  src/AppInstallerCLITests/TestHooks.h
  src/AppInstallerCLITests/TestSource.cpp
  src/AppInstallerCLITests/TestSource.h
  src/AppInstallerCLITests/WorkFlow.cpp
  src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj
  src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj.filters
  src/AppInstallerCommonCore/Filesystem.cpp
  src/AppInstallerCommonCore/PathVariable.cpp
  src/AppInstallerCommonCore/PortableARPEntry.cpp
  src/AppInstallerCommonCore/PortableEntry.cpp
  src/AppInstallerCommonCore/Public/winget/Filesystem.h
  src/AppInstallerCommonCore/Public/winget/PathVariable.h
  src/AppInstallerCommonCore/Public/winget/PortableARPEntry.h
  src/AppInstallerCommonCore/Public/winget/PortableEntry.h
Labels: Issue-Feature

#2429 Update Documentation for schema 1.2
  .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .github/fabricbot.json
  README.md
  doc/ManifestSpecv1.0.md
  doc/windows-package-manager-release-roadmap.md
  doc/windows/package-manager/package/manifest.md
  doc/windows/package-manager/package/windows-package-manager-policies.md
  doc/windows/package-manager/winget/index.md
Labels: Area-Docs
