Repository microsoft/winget-cli, pull requests merged in 2022-04, with the labels that each got.

#2089 Fix exceptions breaking out of the multi-package install loop
  src/AppInstallerCLICore/Workflows/InstallFlow.cpp
Labels: Issue-Bug

#2095 Allow winget to install MS Store packages without account
  src/AppInstallerCLICore/Workflows/MSStoreInstallerHandler.cpp
Labels: Issue-Feature

#2125 Require selection argument on install/show/search/uninstall
  src/AppInstallerCLICore/Argument.cpp
  src/AppInstallerCLICore/Argument.h
  src/AppInstallerCLICore/Commands/InstallCommand.cpp
  src/AppInstallerCLICore/Commands/SearchCommand.cpp
  src/AppInstallerCLICore/Commands/SearchCommand.h
  src/AppInstallerCLICore/Commands/ShowCommand.cpp
  src/AppInstallerCLICore/Commands/ShowCommand.h
  src/AppInstallerCLICore/Commands/UninstallCommand.cpp
  src/AppInstallerCLICore/Resources.h
  src/AppInstallerCLIE2ETests/GroupPolicy.cs
  src/AppInstallerCLIE2ETests/SearchCommand.cs
  src/AppInstallerCLIE2ETests/ShowCommand.cs
  src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
Labels: Issue-Feature, Area-Output
