Repository microsoft/winget-cli, pull requests merged in 2023-06, with the labels that each got.

#3300 Don't read past the end of the HTTP stream
  src/AppInstallerCLITests/Downloader.cpp
  src/AppInstallerCommonCore/HttpStream/HttpClientWrapper.h
  src/AppInstallerCommonCore/HttpStream/HttpLocalCache.cpp
  src/AppInstallerCommonCore/HttpStream/HttpLocalCache.h
  src/AppInstallerCommonCore/Public/AppInstallerDownloader.h
Labels: Issue-Bug

#3341 Update README.md
  README.md
Labels: Issue-Docs

#3299 Stub upgrade self
  .github/actions/spelling/expect.txt
  doc/windows/package-manager/winget/returnCodes.md
  src/AppInstallerCLICore/Argument.cpp
  src/AppInstallerCLICore/Argument.h
  src/AppInstallerCLICore/Commands/ConfigureCommand.cpp
  src/AppInstallerCLICore/Commands/ConfigureCommand.h
  src/AppInstallerCLICore/ExecutionArgs.h
  src/AppInstallerCLICore/Resources.h
  src/AppInstallerCLICore/Workflows/ConfigurationFlow.cpp
  src/AppInstallerCLICore/Workflows/ConfigurationFlow.h
  src/AppInstallerCLICore/Workflows/InstallFlow.cpp
  src/AppInstallerCLICore/Workflows/MSStoreInstallerHandler.cpp
  src/AppInstallerCLICore/Workflows/MSStoreInstallerHandler.h
  src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
  src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj
  src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj.filters
  src/AppInstallerCommonCore/MSStore.cpp
  src/AppInstallerCommonCore/Public/winget/MSStore.h
  src/AppInstallerCommonCore/Public/winget/SelfManagement.h
  src/AppInstallerCommonCore/SelfManagement.cpp
  src/AppInstallerCommonCore/pch.h
  src/AppInstallerSharedLib/Errors.cpp
  src/AppInstallerSharedLib/Public/AppInstallerErrors.h
  src/AppInstallerSharedLib/Public/winget/Runtime.h
  src/AppInstallerSharedLib/Runtime.cpp
Labels: Needs-Author-Feedback

#3296 Refresh process path variable when installing package dependencies
  .github/actions/spelling/expect.txt
  doc/Settings.md
  schemas/JSON/settings/settings.schema.0.2.json
  src/AppInstallerCLICore/Argument.cpp
  src/AppInstallerCLICore/Commands/COMCommand.cpp
  src/AppInstallerCLICore/Commands/InstallCommand.cpp
  src/AppInstallerCLICore/Commands/UpgradeCommand.cpp
  src/AppInstallerCLICore/ExecutionArgs.h
  src/AppInstallerCLICore/Resources.h
  src/AppInstallerCLICore/Workflows/DependenciesFlow.cpp
  src/AppInstallerCLICore/Workflows/InstallFlow.cpp
  src/AppInstallerCLICore/Workflows/InstallFlow.h
  src/AppInstallerCLIE2ETests/InstallCommand.cs
  src/AppInstallerCLIE2ETests/Interop/InstallInterop.cs
  src/AppInstallerCLIE2ETests/TestData/Manifests/TestExeInstaller_PackageDependency.yaml
  src/AppInstallerCLIE2ETests/TestData/Manifests/TestExeInstaller_PackageDependencyRequiresPathRefresh.yaml
  src/AppInstallerCLIE2ETests/TestData/Manifests/TestExeInstaller_PathVariableRefresh.yaml
  src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
  src/AppInstallerCLITests/AppInstallerCLITests.vcxproj
  src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters
  src/AppInstallerCLITests/Dependencies.cpp
  src/AppInstallerCLITests/InstallDependenciesFlow.cpp
  src/AppInstallerCLITests/PathVariable.cpp
  src/AppInstallerCLITests/Strings.cpp
  src/AppInstallerCommonCore/PathVariable.cpp
  src/AppInstallerCommonCore/Public/winget/PathVariable.h
  src/AppInstallerCommonCore/Public/winget/UserSettings.h
  src/AppInstallerCommonCore/UserSettings.cpp
  src/AppInstallerSharedLib/AppInstallerStrings.cpp
  src/AppInstallerSharedLib/Public/AppInstallerStrings.h
  src/AppInstallerTestExeInstaller/main.cpp
  src/IndexCreationTool/Program.cs
  src/Microsoft.Management.Deployment/InstallOptions.cpp
  src/Microsoft.Management.Deployment/InstallOptions.h
  src/Microsoft.Management.Deployment/PackageManager.cpp
  src/Microsoft.Management.Deployment/PackageManager.idl
Labels: Issue-Bug, Area-Path

#3389 Network troubleshooting
  doc/troubleshooting/README.md
Labels: Issue-Docs
