Repository microsoft/winget-cli, pull requests merged in 2023-07, with the labels that each got.

#3422 Disable RTTI
  .github/actions/spelling/expect.txt
  src/AppInstallerCLI/AppInstallerCLI.vcxproj
  src/AppInstallerCLICore/AppInstallerCLICore.vcxproj
  src/AppInstallerCLITests/AppInstallerCLITests.vcxproj
  src/AppInstallerCLITests/TestSource.cpp
  src/AppInstallerCLITests/TestSource.h
  src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj
  src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj
  src/AppInstallerRepositoryCore/CompositeSource.cpp
  src/AppInstallerRepositoryCore/CompositeSource.h
  src/AppInstallerRepositoryCore/ISource.h
  src/AppInstallerRepositoryCore/Microsoft/ConfigurableTestSourceFactory.cpp
  src/AppInstallerRepositoryCore/Microsoft/SQLiteIndexSource.cpp
  src/AppInstallerRepositoryCore/Microsoft/SQLiteIndexSource.h
  src/AppInstallerRepositoryCore/PackageTrackingCatalog.cpp
  src/AppInstallerRepositoryCore/Public/winget/RepositorySearch.h
  src/AppInstallerRepositoryCore/RepositorySource.cpp
  src/AppInstallerRepositoryCore/Rest/RestSource.cpp
  src/AppInstallerRepositoryCore/Rest/RestSource.h
  src/Microsoft.Management.Configuration.OutOfProc/Microsoft.Management.Configuration.OutOfProc.vcxproj
  src/Microsoft.Management.Deployment.InProc/Microsoft.Management.Deployment.InProc.vcxproj
  src/Microsoft.Management.Deployment/Microsoft.Management.Deployment.vcxproj
  src/PureLib/PureLib.vcxproj
  src/WinGetServer/WinGetServer.vcxproj
  src/WinGetUtil/WinGetUtil.vcxproj
  src/WindowsPackageManager/WindowsPackageManager.vcxproj
  src/cpprestsdk/cpprestsdk.vcxproj
Labels: Issue-Feature

#3478 Upgrade 1.6 schema to 2020-12
  schemas/JSON/manifests/v1.6.0/manifest.defaultLocale.1.6.0.json
  schemas/JSON/manifests/v1.6.0/manifest.installer.1.6.0.json
  schemas/JSON/manifests/v1.6.0/manifest.locale.1.6.0.json
  schemas/JSON/manifests/v1.6.0/manifest.singleton.1.6.0.json
  schemas/JSON/manifests/v1.6.0/manifest.version.1.6.0.json
Labels: Issue-Feature, Area-Manifest

#3473 Allow `--include-unknown` in list `--upgrade-available`
  src/AppInstallerCLICore/Argument.cpp
  src/AppInstallerCLICore/Argument.h
  src/AppInstallerCLICore/Commands/ListCommand.cpp
  src/AppInstallerCLICore/Commands/ListCommand.h
  src/AppInstallerCLICore/Resources.h
  src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
Labels: Issue-Bug
