Repository microsoft/winget-cli, pull requests merged in 2024-08, with the labels that each got.

#4674 PowerShell Help for Microsoft.WinGet.Client
  .github/actions/spelling/excludes.txt
  .github/actions/spelling/expect.txt
  .github/actions/spelling/patterns.txt
  src/PowerShell/Help/Microsoft.WinGet.Client/Add-WinGetSource.md
  src/PowerShell/Help/Microsoft.WinGet.Client/Assert-WinGetPackageManager.md
  src/PowerShell/Help/Microsoft.WinGet.Client/Disable-WinGetSetting.md
  src/PowerShell/Help/Microsoft.WinGet.Client/Enable-WinGetSetting.md
  src/PowerShell/Help/Microsoft.WinGet.Client/Export-WinGetPackage.md
  src/PowerShell/Help/Microsoft.WinGet.Client/Find-WinGetPackage.md
  src/PowerShell/Help/Microsoft.WinGet.Client/Get-WinGetPackage.md
  src/PowerShell/Help/Microsoft.WinGet.Client/Get-WinGetSettings.md
  src/PowerShell/Help/Microsoft.WinGet.Client/Get-WinGetSource.md
  src/PowerShell/Help/Microsoft.WinGet.Client/Get-WinGetUserSettings.md
  src/PowerShell/Help/Microsoft.WinGet.Client/Get-WinGetVersion.md
  src/PowerShell/Help/Microsoft.WinGet.Client/Install-WinGetPackage.md
  src/PowerShell/Help/Microsoft.WinGet.Client/Microsoft.WinGet.Client.md
  src/PowerShell/Help/Microsoft.WinGet.Client/Remove-WinGetSource.md
  src/PowerShell/Help/Microsoft.WinGet.Client/Repair-WinGetPackageManager.md
  src/PowerShell/Help/Microsoft.WinGet.Client/Reset-WinGetSource.md
  src/PowerShell/Help/Microsoft.WinGet.Client/Set-WinGetUserSettings.md
  src/PowerShell/Help/Microsoft.WinGet.Client/Test-WinGetUserSettings.md
  src/PowerShell/Help/Microsoft.WinGet.Client/Uninstall-WinGetPackage.md
  src/PowerShell/Help/Microsoft.WinGet.Client/Update-WinGetPackage.md
  src/PowerShell/Help/markdownlint.yaml
Labels: Issue-Docs, Needs-Author-Feedback, Needs-Attention

#4740 Remove preference for "installed" installer type
  src/AppInstallerCLICore/Workflows/ManifestComparator.cpp
  src/AppInstallerCLITests/ManifestComparator.cpp
Labels: Issue-Bug

#4746 External HR error message support
  src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
  src/AppInstallerSharedLib/Errors.cpp
Labels: Issue-Feature
