Repository microsoft/winget-cli, pull requests merged in 2024-10, with the labels that each got.

#4841 More messages for common Store package download scenarios
  doc/windows/package-manager/winget/returnCodes.md
  src/AppInstallerCLICore/Resources.h
  src/AppInstallerCLICore/Workflows/MSStoreInstallerHandler.cpp
  src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
  src/AppInstallerCLITests/MSStoreDownloadFlow.cpp
  src/AppInstallerCLITests/MsixInfo.cpp
  src/AppInstallerCommonCore/MSStoreDownload.cpp
  src/AppInstallerCommonCore/Manifest/ManifestCommon.cpp
  src/AppInstallerCommonCore/MsixInfo.cpp
  src/AppInstallerCommonCore/Public/AppInstallerMsixInfo.h
  src/AppInstallerCommonCore/Public/winget/ManifestCommon.h
  src/AppInstallerSharedLib/Errors.cpp
  src/AppInstallerSharedLib/Public/AppInstallerErrors.h
Labels: Issue-Feature, Area-Output

#4866 Make dependency lookup case insensitive
  src/AppInstallerCLITests/SQLiteIndex.cpp
  src/AppInstallerRepositoryCore/Microsoft/Schema/1_4/DependenciesTable.cpp
Labels: Issue-Bug

#4886 Add experimental feature for font list command
  .github/actions/spelling/expect.txt
  schemas/JSON/settings/settings.schema.0.2.json
  src/AppInstallerCLICore/AppInstallerCLICore.vcxproj
  src/AppInstallerCLICore/AppInstallerCLICore.vcxproj.filters
  src/AppInstallerCLICore/Argument.cpp
  src/AppInstallerCLICore/Commands/FontCommand.cpp
  src/AppInstallerCLICore/Commands/FontCommand.h
  src/AppInstallerCLICore/Commands/RootCommand.cpp
  src/AppInstallerCLICore/ExecutionArgs.h
  src/AppInstallerCLICore/Resources.h
  src/AppInstallerCLICore/Workflows/FontFlow.cpp
  src/AppInstallerCLICore/Workflows/FontFlow.h
  src/AppInstallerCLIE2ETests/BaseCommand.cs
  src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
  src/AppInstallerCLITests/AppInstallerCLITests.vcxproj
  src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters
  src/AppInstallerCLITests/Fonts.cpp
  src/AppInstallerCLITests/Versions.cpp
  src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj
  src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj.filters
  src/AppInstallerCommonCore/ExperimentalFeature.cpp
  src/AppInstallerCommonCore/Fonts.cpp
  src/AppInstallerCommonCore/Locale.cpp
  src/AppInstallerCommonCore/Public/AppInstallerRuntime.h
  src/AppInstallerCommonCore/Public/winget/ExperimentalFeature.h
  src/AppInstallerCommonCore/Public/winget/Fonts.h
  src/AppInstallerCommonCore/Public/winget/Locale.h
  src/AppInstallerCommonCore/Public/winget/UserSettings.h
  src/AppInstallerCommonCore/Runtime.cpp
  src/AppInstallerCommonCore/UserSettings.cpp
  src/AppInstallerSharedLib/Public/AppInstallerVersions.h
  src/AppInstallerSharedLib/Versions.cpp
Labels: Needs-Attention
